YAML inclusion of copy unity_config

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -22,6 +22,10 @@ jobs:
       
       - name: Clean PlatformIO build
         run: pio run --target clean
+      
+      - name: Copy unity_config.h into Unity library folder
+        run: |
+          cp include/unity_config.h .pio/libdeps/uno/Unity/src/unity_config.h || echo "unity_config.h not found"
 
       - name: Build with PlatformIO
         run: pio run
